"""added password hash to user table

Revision ID: 421ae2c0f8d5
Revises: 0b604ca1dcce
Create Date: 2020-01-02 11:31:11.317939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421ae2c0f8d5'
down_revision = '0b604ca1dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
